name: Auto Scrape Fog Images

on:
    schedule:
        - cron: '0,15,30,45 * * * *'

    workflow_dispatch:

jobs:
  scrape-and-save:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Install Tesseract OCR
        run: |
          sudo apt-get update
          sudo apt-get install -y tesseract-ocr tesseract-ocr-chi-sim
          
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          
      - name: Install Python dependencies
        run: |
          cd 时刻爬取
          pip install -r requirements.txt
          
      - name: Run Scraper
        run: |
          cd 时刻爬取
          python main.py
          
      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || git commit -m "自动抓取最新图片和更新表格"
          git push
